# apt-listchanges Japanese
# Copyright (C) 2002
# Junichi Uekawa <dancer@debian.org>, 2002, 2005
# Hideki Yamane <henrich@debian.org>, 2017
msgid ""
msgstr ""
"Project-Id-Version: apt-listchanges\n"
"Report-Msgid-Bugs-To: apt-listchanges@packages.debian.org\n"
"POT-Creation-Date: 2019-11-03 20:05+0100\n"
"PO-Revision-Date: 2017-10-29 05:54+0900\n"
"Last-Translator: Hideki Yamane <henrich@debian.org>\n"
"Language-Team: Japanese \n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8-bit\n"
"Generated-By: pygettext.py 1.4\n"

#: ../apt-listchanges.py:62
#, python-format
msgid "Unknown frontend: %s"
msgstr "不明なフロントエンド: %s"

#: ../apt-listchanges.py:78
#, python-format
msgid "Cannot reopen /dev/tty for stdin: %s"
msgstr "標準入力に対して /dev/tty を再オープンできません: %s"

#: ../apt-listchanges.py:133
#, python-format
msgid "News for %s"
msgstr "%s のニュース"

#: ../apt-listchanges.py:135
#, python-format
msgid "Changes for %s"
msgstr "%s の変更点"

#: ../apt-listchanges.py:145
msgid "Informational notes"
msgstr "情報メモ"

#: ../apt-listchanges.py:152
msgid "apt-listchanges: News"
msgstr "apt-listchanges: ニュース"

#: ../apt-listchanges.py:153
msgid "apt-listchanges: Changelogs"
msgstr "apt-listchanges: Changelog "

#: ../apt-listchanges.py:159
#, python-format
msgid "apt-listchanges: news for %s"
msgstr "apt-listchanges: %s のニュース"

#: ../apt-listchanges.py:160
#, python-format
msgid "apt-listchanges: changelogs for %s"
msgstr "apt-listchanges: %s の changelog "

#: ../apt-listchanges.py:166
msgid "Didn't find any valid .deb archives"
msgstr "有効な .deb アーカイブを見付ける事ができませんでした"

#: ../apt-listchanges.py:183
#, python-format
msgid "%s: will be newly installed"
msgstr "%s: を新規にインストールします"

#: ../apt-listchanges.py:210
#, python-format
msgid "%(pkg)s: Version %(version)s has already been seen"
msgstr "%(pkg)s: バージョン %(version)s は閲覧済みです"

#: ../apt-listchanges.py:214
#, python-format
msgid ""
"%(pkg)s: Version %(version)s is lower than version of related packages "
"(%(maxversion)s)"
msgstr ""
"%(pkg)s: バージョン %(version)s は関連するパッケージのバージョン "
"(%(maxversion)s) より低いです"

#: ../apt-listchanges.py:268
msgid "Binary NMU of"
msgstr ""

#: ../apt-listchanges.py:302
#, python-format
msgid "Received signal %d, exiting"
msgstr "シグナル %d を受け取りました、終了します"

#: ../apt-listchanges/apt_listchanges.py:55
msgid "Aborting"
msgstr "強制終了します"

#: ../apt-listchanges/apt_listchanges.py:60
#, python-format
msgid "Confirmation failed: %s"
msgstr "確認が失敗しました: %s"

#: ../apt-listchanges/apt_listchanges.py:64
#, python-format
msgid "Mailing %(address)s: %(subject)s"
msgstr "%(address)s にメール: %(subject)s"

#: ../apt-listchanges/apt_listchanges.py:83
#, python-format
msgid "Failed to send mail to %(address)s: %(errmsg)s"
msgstr "%(address)s 宛メールの送信に失敗しました: %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:92
#, python-format
msgid "The mail frontend needs an installed 'sendmail', using %s"
msgstr ""
"メールフロントエンドは 'sendmail' がインストールされている必要があるので、%s "
"を使います"

#: ../apt-listchanges/apt_listchanges.py:98
#, python-format
msgid "The mail frontend needs an e-mail address to be configured, using %s"
msgstr ""
"メールフロントエンドにはメールアドレスが設定されている必要があるので、%s を使"
"います"

#: ../apt-listchanges/apt_listchanges.py:111
msgid "Available apt-listchanges frontends:"
msgstr "利用可能な apt-listchanges のフロントエンド:"

#: ../apt-listchanges/apt_listchanges.py:113
msgid "Choose a frontend by entering its number: "
msgstr "番号を入力してフロントエンドを選択して下さい:"

#: ../apt-listchanges/apt_listchanges.py:122
#: ../apt-listchanges/apt_listchanges.py:431
#, python-format
msgid "Error: %s"
msgstr "エラー: %s"

#: ../apt-listchanges/apt_listchanges.py:124
#, python-format
msgid "Using default frontend: %s"
msgstr "デフォルトのフロントエンドを利用します: %s"

#: ../apt-listchanges/apt_listchanges.py:167
#, python-format
msgid "$DISPLAY is not set, falling back to %(frontend)s"
msgstr "$DISPLAY が設定されていません、%(frontend)s にフォールバックします"

#: ../apt-listchanges/apt_listchanges.py:187
#, python-format
msgid ""
"The gtk frontend needs a working python3-gi,\n"
"but it cannot be loaded. Falling back to %(frontend)s.\n"
"The error is: %(errmsg)s"
msgstr ""
"GTK フロントエンドは動作中の python3-gi を必要としますが、\n"
"ロードできませんでした。%(frontend)s にフォールバックします。\n"
"エラー内容: %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:288
msgid "Do you want to continue? [Y/n] "
msgstr "これでよろしいですか [Y(はい)/n(いいえ)] "

#: ../apt-listchanges/apt_listchanges.py:301
#: ../apt-listchanges/apt_listchanges.py:327
#: ../apt-listchanges/apt_listchanges.py:335
msgid "Reading changelogs"
msgstr "changelog を読み込んでいます"

#: ../apt-listchanges/apt_listchanges.py:335
msgid "Done"
msgstr "完了"

#: ../apt-listchanges/apt_listchanges.py:368
#, python-format
msgid "Command %(cmd)s exited with status %(status)d"
msgstr "コマンド %(cmd)s が終了コード %(status)d で終了しました"

#: ../apt-listchanges/apt_listchanges.py:413
#, python-format
msgid "Found user: %(user)s, temporary directory: %(dir)s"
msgstr "見つかったユーザー: %(user)s, 一時ディレクトリ: %(dir)s"

#: ../apt-listchanges/apt_listchanges.py:459
#, python-format
msgid "Error getting user from variable '%(envvar)s': %(errmsg)s"
msgstr "変数 '%(envvar)s' からユーザーの取得がエラーになりました: %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:465
msgid "Cannot find suitable user to drop root privileges"
msgstr "root 特権を落とすのに適切なユーザーを見つけられません"

#: ../apt-listchanges/apt_listchanges.py:491
#, python-format
msgid ""
"None of the following directories is accessible by user %(user)s: %(dirs)s"
msgstr ""
"以下のディレクトリはいずれもユーザー %(user)s からアクセスできません: "
"%(dirs)s"

#: ../apt-listchanges/apt_listchanges.py:521
msgid "press q to quit"
msgstr "終了するには q を押して下さい"

#: ../apt-listchanges/ALCConfig.py:88
#, python-format
msgid "Unknown configuration file option: %s"
msgstr "不明な設定ファイルオプション: %s"

#: ../apt-listchanges/ALCConfig.py:101
msgid "Usage: apt-listchanges [options] {--apt | filename.deb ...}\n"
msgstr "使用方法: apt-listchanges [オプション] {--apt | ファイル名.deb ...}\n"

#: ../apt-listchanges/ALCConfig.py:107
#, python-format
msgid "Unknown argument %(arg)s for option %(opt)s.  Allowed are: %(allowed)s."
msgstr ""
"オプション %(opt)s に不明な引数 %(arg)s が与えられました。 可能なオプション"
"は: %(allowed)s です。"

#: ../apt-listchanges/ALCConfig.py:119
#, python-format
msgid "%(deb)s does not have '.deb' extension"
msgstr "%(deb)s に '.deb' 拡張子がありません"

#: ../apt-listchanges/ALCConfig.py:122
#, python-format
msgid "%(deb)s does not exist or is not a file"
msgstr "%(deb)s が存在しない、あるいはファイルではありません"

#: ../apt-listchanges/ALCConfig.py:125
#, python-format
msgid "%(deb)s is not readable"
msgstr "%(deb)s は読み取れません"

#: ../apt-listchanges/ALCConfig.py:216
msgid "--since=<version> and --show-all are mutually exclusive"
msgstr "--since=<version> および --show-all は相互に排他です"

#: ../apt-listchanges/ALCConfig.py:224
msgid "--since=<version> expects a path to exactly one .deb archive"
msgstr "--since=<version> は厳密に一つの .deb アーカイブへのパスを要求します"

#: ../apt-listchanges/DebianFiles.py:119 ../apt-listchanges/DebianFiles.py:128
#, python-format
msgid "Error processing '%(what)s': %(errmsg)s"
msgstr "エラー処理中 '%(what)s': %(errmsg)s"

#: ../apt-listchanges/DebianFiles.py:337
#, python-format
msgid "Ignoring `%s' (seems to be a directory!)"
msgstr "「%s」を無視します (ディレクトリのようです!)"

#: ../apt-listchanges/DebianFiles.py:410
#, python-format
msgid "Calling %(cmd)s to retrieve changelog"
msgstr "changelog の取得のため、%(cmd)s をコール中"

#: ../apt-listchanges/DebianFiles.py:414
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; 'apt-get changelog' failed "
"with: %(errmsg)s"
msgstr ""
"パッケージ %(pkg)s の changelog が取得できません; 'apt-get changelog' は以下"
"の問題で失敗しました: %(errmsg)s"

#: ../apt-listchanges/DebianFiles.py:420
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; could not run 'apt-get "
"changelog': %(errmsg)s"
msgstr ""
"Unable to retrieve changelog for package %(pkg)s; 'apt-get changelog' を実行"
"できませんでした: %(errmsg)s"

#: ../apt-listchanges/AptListChangesGtk.py:40
msgid "apt-listchanges: Reading changelogs"
msgstr "apt-listchanges: changelog を読み取り中"

#: ../apt-listchanges/AptListChangesGtk.py:41
msgid "Reading changelogs. Please wait."
msgstr "changelog を読み込んでいます。お待ち下さい。"

#: ../apt-listchanges/AptListChangesGtk.py:74
msgid "Continue Installation?"
msgstr "インストールを継続しますか?"

#: ../apt-listchanges/AptListChangesGtk.py:75
msgid ""
"Select <i>yes</i> to continue with the installation.\n"
"Select <i>no</i> to abort the installation."
msgstr ""

#: ../apt-listchanges/ALCApt.py:55
msgid "APT pipeline messages:"
msgstr "APT パイプラインメッセージ:"

#: ../apt-listchanges/ALCApt.py:63
msgid "Packages list:"
msgstr "パッケージ一覧:"

#: ../apt-listchanges/ALCApt.py:71
msgid ""
"APT_HOOK_INFO_FD environment variable is not defined\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD set to 20?)"
msgstr ""
"APT_HOOK_INFO_FD が設定されていません\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD が 20 に設定されてい"
"ますか?"

#: ../apt-listchanges/ALCApt.py:77
msgid "Invalid (non-numeric) value of APT_HOOK_INFO_FD environment variable"
msgstr "正しくない (数値ではない) 値の APT_HOOK_INFO_FD 環境変数"

#: ../apt-listchanges/ALCApt.py:80
#, python-format
msgid "Will read apt pipeline messages from file descriptor %d"
msgstr ""
"ファイルディスクリプタ %d から apt パイプラインメッセージを読み取りますか"

#: ../apt-listchanges/ALCApt.py:83
msgid ""
"Incorrect value (0) of APT_HOOK_INFO_FD environment variable.\n"
"If the warning persists after restart of the package manager (e.g. "
"aptitude),\n"
"please check if the /etc/apt/apt.conf.d/20listchanges file was properly "
"updated."
msgstr ""
"APT_HOOK_INFO_FD 環境変数の正しくない値 (0)。\n"
"パッケージマネージャー (例: aptitude) を再起動後も警告が出続ける場合は、\n"
"/etc/apt/apt.conf.d/20listchanges ファイルが正しく更新されてるかどうかを確認"
"して下さい。"

#: ../apt-listchanges/ALCApt.py:88
msgid ""
"APT_HOOK_INFO_FD environment variable is incorrectly defined\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD should be greater "
"than 2)."
msgstr ""
"APT_HOOK_INFO_FD 環境変数が間違って定義されています\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version は 2 より大きい必要"
"があります)。"

#: ../apt-listchanges/ALCApt.py:94
#, python-format
msgid "Cannot read from file descriptor %(fd)d: %(errmsg)s"
msgstr "ファイルディスクリプタ %(fd)d から読み取りが出来ません: %(errmsg)s"

#: ../apt-listchanges/ALCApt.py:100
msgid ""
"Wrong or missing VERSION from apt pipeline\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version set to 2?)"
msgstr ""
"apt のパイプラインから渡された VERSION が間違っているか、もしくはありませ"
"ん。\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version は 2 に設定されてい"
"ますか?)"

#: ../apt-listchanges/ALCLog.py:30 ../apt-listchanges/ALCLog.py:36
#, python-format
msgid "apt-listchanges: %(msg)s"
msgstr "apt-listchanges: %(msg)s"

#: ../apt-listchanges/ALCLog.py:33
#, python-format
msgid "apt-listchanges warning: %(msg)s"
msgstr "apt-listchanges 警告: %(msg)s"

#: ../apt-listchanges/ALCSeenDb.py:55
msgid ""
"Path to the seen database is unknown.\n"
"Please either specify it with --save-seen option\n"
"or pass --profile=apt to have it read from the configuration file."
msgstr ""
"閲覧済みデータベースへのパスが不明です。\n"
"--save-seen オプションで指定する、または --profile=apt を指定して\n"
"設定ファイルから読み取ってください。"

#: ../apt-listchanges/ALCSeenDb.py:66
#, python-format
msgid "Database %(db)s does not end with %(ext)s"
msgstr "データベース %(db)s は %(ext)s で終わっていません"

#: ../apt-listchanges/ALCSeenDb.py:75
#, python-format
msgid "Database %(db)s failed to load: %(errmsg)s"
msgstr "データベース %(db)s をロードするのに失敗しました: %(errmsg)s"

#: ../apt-listchanges/apt-listchanges.ui:13
msgid "List the changes"
msgstr "変更点一覧"

#: ../apt-listchanges/apt-listchanges.ui:43
msgid ""
"The following changes are found in the packages you are about to install:"
msgstr "以下の変更点がインストールしようとしているパッケージに見つかりました:"

#~ msgid "You can abort the installation if you select 'no'."
#~ msgstr "「いいえ」を選択することでインストールを中止することができます。"
